name: 'Minebbs-Auto-Release'
description: 'Automatically publish resource updates to Minebbs'
author: 'HuoHua'

inputs:
  resources:
    required: true
    description: "Minebbs资源ID (数字)"
  token:
    required: true
    description: "Minebbs API Token (从仓库Secrets获取)"
  title:
    required: true
    description: "更新标题 (通常使用版本号如 v1.0.0)"
    default: "v0.0.1"
  new_version:
    required: true
    description: "新版本号"
    default: "v0.0.1"
  description_file:
    required: false
    description: "更新描述文件路径 (与description二选一)"
    default: "./CHANGELOG.md"
  description:
    required: false
    description: "更新描述文本 (与description_file二选一)"
  file_url:
    required: true
    description: "资源下载URL (通常指向GitHub Releases)"
    default: "https://github.com/<author>/<repo>/releases/latest"

branding:
  icon: 'archive'
  color: 'blue'

runs:
  using: 'node20'
  main: 'dist/index.js'