name: 'Minebbs-Auto-Release'
description: 'Automatic release of versions of Minebbs resources'
author: 'HuoHua'
inputs: {}
branding:
  icon: 'archive'  
  color: 'blue'
runs:
  using: 'node16'
  main: 'dist/index.js'

  
  
