name: 'build-test'
on: # rebuild any PRs and main branch changes
  pull_request:
  push:
    paths:
      - 'src/*.ts'
      - '.github/workflows/test.yml'
      

jobs:
  build: # make sure build/ci work properly
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '20'

      - run: npm install
      
      - run: npm run build

      - name: Test Minebbs Release
        uses: ./
        if: success() && startsWith(github.ref, 'refs/tags/')
        with: 
          resources: '4542'
          token: ${{ secrets.MINEBBSKEY }}
          title: ${{ github.ref_name }}
          new_version: ${{ github.ref_name }}
          description_file: './CHANGELOG.md'
          file_url: 'https://github.com/HuoHuas001/Minebbs-Auto-Release/releases/latest'

      - name: Release on GitHub
        uses: softprops/action-gh-release@v1
        if: success() && startsWith(github.ref, 'refs/tags/')
        with:
          name: ${{ github.ref_name }}
          body_path: ./CHANGELOG.md
        env:
            GITHUB_REPOSITORY: HuoHuas001/Minebbs-Auto-Release

